coverage:
  status:
    project:
      default:
        threshold: "0%"
        informational: true
    patch:
      default:
        threshold: "0%"
        informational: true

comment:
  layout: "header, files, footer"
  require_changes: false  # if true: only post the comment if coverage changes
  require_head: false
  require_base: false
  hide_project_coverage: false