coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "header, diff, flags"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes