coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "header, diff, flags, files"
  require_changes: false  # if true: only post the comment if coverage changes
  require_head: false
  require_base: false
  hide_project_coverage: false