name: Coding Style Check

on:
    pull_request:
        branches:
            - main
        paths:
            - '.github/workflows/coding_style_check.yml'
            - 'include/**'
            - 'src/**'
            - 'module/**'
jobs:
    cpplint_check:
        runs-on: lynx-ubuntu-22.04-medium
        timeout-minutes: 30
        steps:
          - name: Python Setup
            uses: actions/setup-python@v5
            with:
                python-version: '3.13'
          - name: Download Source
            uses: actions/checkout@v4.2.2
            with:
                fetch-depth: 10
                ref: ${{ github.event.pull_request.head.sha }}
          - name: Sync Dependencies
            uses: ./.github/actions/sync-deps
          - name: cpplint check
            run: |
                python tools/cpplint_check.py ${{ github.event.pull_request.base.sha }}
          - name: coding style check
            run: |
                python tools/code_format_check.py ${{ github.event.pull_request.base.sha }}
